### ISSUE TITLE
Event exclusion ("except" parameter) not working

### ISSUE THREAD

**Issue by Bruno-Meowtel** [notamedia/yii2-sentry#55] opened 2021-06-22 22:52 UTC
When trying to use the [**except**](https://www.yiiframework.com/doc/api/2.0/yii-log-target#$except-detail) property to prevent specific exceptions to be logged, these are still sent to Sentry.

Yii: **2.0.36**
Yii2-Sentry: **1.6.0b**

**Configuration:**
```
'log' => [
            'targets' => [
                [
                    'class' => 'notamedia\sentry\SentryTarget',
                    'except' => [
                        'yii\web\HttpException:404',
                        'yii\web\NotFoundHttpException',
                        'yii\web\UnauthorizedHttpException'
                    ],
                    'dsn' => $params['sentry']['dsn'],
                    'levels' => $params['sentry']['levels'],
                    'context' => $params['sentry']['context']
                ]
            ]
        ],
```

According to the CHANGELOG it seems it was [fixed in v1.5.1](https://github.com/notamedia/yii2-sentry/blob/master/CHANGELOG.md#151---2020-08-24), am I missing something? 😊

**Comment by CookiesEater** [comment] 2021-06-25 09:30
Hmm, should work because except is Yii mechanism for any logs
Can you check, please, in Sentry `category` tag for issues: is same as you write to `except`?

**Comment by orionchikby** [comment] 2021-08-10 09:32
$excluded_exceptions => [
    'yii\web\HttpException:404',
    'yii\web\NotFoundHttpException',
    'yii\web\UnauthorizedHttpException'
];

....

'clientOptions' => [
    'excluded_exceptions' => $excluded_exceptions,
],
'except' => $excluded_exceptions, 
....

**Comment by CookiesEater** [comment] 2021-10-25 10:59
Closing because cannot reproduce to fix. Fill free to reopen if it still present.

**Closed as completed by CookiesEater** 2021-10-25 10:59 UTC
